In [1]:
import pandas as pd
import numpy as np

In [2]:
a= np.eye(5, dtype=int)

In [3]:
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [4]:
a=np.array(range(12)).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
a=np.array(range(12)).reshape((6,-1))
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [8]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [14]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
lst = [[1,2,3],
      [4,5,6],
      [7,8,9]]
arr=np.array(lst)

a= arr[0:2, 0:2]
print(a)

[[1 2]
 [4 5]]


In [20]:
a= arr[1:,1:]
print(a)

[[5 6]
 [8 9]]


In [21]:
a=[0,1,2,3]
b=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(a[:2])

[0, 1]
